#!/bin/bash

usage()
{
cat << EOF

usage: $0 options

hurl is synonymous for curl with hmac auth

OPTIONS:
   -h      this help message
   -p      auth profile to use (default points to ~/.hurl/default.conf)
   -a      api key 
   -s      secret key
   -c      configure a current session to use a temp apikey/secret

EOF
}

HURL_PROFILE="default"
ARGS=""
VERBOSE=""

while [[ $# > 0 ]]; do
	key="$1"
	shift
	case $key in
	    -p|--profile)
	    HURL_PROFILE="$1"
	    shift
	    ;;
	    -h|--help)
	    usage
	    ARGS="$ARGS $key"
	    ;;
	    -a|--api-key)
	    HURL_API_KEY="$1"
	    shift
	    ;;
	    -s|--secret-key)
	    HURL_SECRET_KEY="$1"
	    shift
	    ;;
	    -c|--configure)
	    CONFIGURE="true"
	    ;;
	    -v|--verbose)
	    VERBOSE="true"
	    ARGS="$ARGS $key"
	    ;;
	    *)
		ARGS="$ARGS $key"
		;;
	esac
done

if [ ! -f ~/.hurl/$HURL_PROFILE.conf ]; then
	[[ ! -z "$VERBOSE" ]] && echo "~/.hurl/$HURL_PROFILE.conf not found, using env variables"
else
	[[ -z "$HURL_API_KEY" ]] && export HURL_API_KEY="$(grep apiKey ~/.hurl/$HURL_PROFILE.conf | awk '{ print $2 }')"
	[[ -z "$HURL_SECRET_KEY" ]] && export HURL_SECRET_KEY="$(grep secret ~/.hurl/$HURL_PROFILE.conf | awk '{ print $2 }')"
fi

if [[ -z "$HURL_API_KEY" || -z "$HURL_SECRET_KEY" || ! -z $CONFIGURE ]]; then
	echo -n "Enter Hurl ApiKey [**** ${HURL_API_KEY:(-4)}]: " && read HURL_API_KEY
    echo -n "Enter Hurl Secret [**** ${HURL_SECRET_KEY:(-4)}]: " && read HURL_SECRET_KEY
fi

ARGS=$(echo ${ARGS} | sed -e 's/^ *//g;s/ *$//g')

if [ -z "$ARGS" ]; then
	echo "Missing url argument to connect to..."
	exit -1
fi

if [ ! -z "$VERBOSE" ]; then
	echo "Using ApiKey: ****${HURL_API_KEY:(-4)}"
	echo "Using Secret: ****${HURL_SECRET_KEY:(-4)}"
	echo "Using Arguments: $ARGS"
	echo "Executing: java -jar "$(dirname "$0")"/target/jersey-hmac-auth-cli-*.jar --apiKey "$HURL_API_KEY" --secretKey "$HURL_SECRET_KEY" $ARGS"
fi

java -jar "$(dirname "$0")"/target/jersey-hmac-auth-cli-*.jar --apiKey "$HURL_API_KEY" --secretKey "$HURL_SECRET_KEY" $ARGS
